name: Make Release
on: workflow_dispatch

jobs:
  release_create:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Bump version
      run: >-
        bin/bump_version.py

    - name: Commit updated version.py
      id: commit_updated
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add meshtastic_flasher/version.py
        git commit -m "bump version" && git push || echo "No changes to commit"
        git log -n 1 --pretty=format:"%H" | tail -n 1 | awk '{print "::set-output name=sha::"$0}'

    - name: Get version
      id: get_version
      run: >-
        bin/show_version.py

    - name: Create GitHub release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: true
        release_name: Meshtastic Flasher ${{ steps.get_version.outputs.version }}
        tag_name: ${{ steps.get_version.outputs.version }}
        body: |
          Autogenerated by github action, developer should edit as required before publishing...
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
